### ISSUE TITLE
Oozie WF submission via Hue

### ISSUE THREAD

**Issue by celamb4** [hdinsight/Iaas-Applications#19]
When submitting a Workflow through Oozie filebrowser, Hue seems to remove the first '/' in the oozie.worflow.path. This version of Hue seems to have limited functionality so not sure where to make changes. I also see an authentication issue at the end. 

To recreate. 
1) Create a workflow.xml
2) Upload to HDFS using Hue. 
3) Click on workflow.xml and submit.

> Error submitting job path/to/workflow//workflow.xml
> E0504: App directory [path/to/workflow//workflow.xml] does not exist

Trace:
```

[21/Feb/2018 15:42:28 -0800] middleware   INFO     Processing exception: Error submitting job path/to/workflow//workflow.xml: Traceback (most recent call last):
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/share/hue/apps/oozie/src/oozie/views/dashboard.py", line 775, in submit_external_job
    raise PopupException(_("Error submitting job %s") % (application_path,), detail=detail)
PopupException: Error submitting job path/to/workflow//workflow.xml
[21/Feb/2018 15:42:28 -0800] dashboard    ERROR    E0504: App directory [path/to/workflow//workflow.xml] does not exist
Traceback (most recent call last):
  File "/usr/share/hue/apps/oozie/src/oozie/views/dashboard.py", line 767, in submit_external_job
    job_id = submission.run(application_path)
  File "/usr/share/hue/desktop/libs/liboozie/src/liboozie/submittion.py", line 85, in run
    self.oozie_id = self.api.submit_job(self.properties)
  File "/usr/share/hue/desktop/libs/liboozie/src/liboozie/oozie_api.py", line 237, in submit_job
    resp = self._root.post('jobs', params, data=config_gen(properties), contenttype=_XML_CONTENT_TYPE)
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 122, in post
    return self.invoke("POST", relpath, params, data, self._make_headers(contenttype, headers))
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 78, in invoke
    urlencode=self._urlencode)
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 161, in execute
    raise self._exc_class(ex)
RestException: <html><head><title>Apache Tomcat/6.0.48 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 401 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.48</h3></body></html> (error 401)
```

**Comment by aaneja** [comment]
We've not been maintaining the Hue as an edgenode install script. If you're up to it, you're welcome to submit a PR to update the install script!
You may have already seen this, but for submitting Oozie workflows you can try the steps mentioned [here].(https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-use-oozie-linux-mac)
